[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[start]
  cmd = "npm run dev"
  runIn = "service"

[service "backend"]
  startCommand = "cd backend && npm start"
  envVars = { 
    MONGO_URI = "mongodb+srv://0802shruti04:kZpEOuy0cSfaRVRY@cluster0.ainsa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",
    PORT = "4000"
  }

[service "frontend"]
  startCommand = "cd frontend && npm run dev"
  envVars = { 
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Y29zbWljLXRocnVzaC0zLmNsZXJrLmFjY291bnRzLmRldiQ",
    CLERK_SECRET_KEY = "sk_test_llSk0cpFlwGseFJ9rA7rTQB08G8ZXN0A2IUd5VH1iZ"
  }
