[backend]
  service = "backend"
  start = "node app.js"
  env = { 
    MONGO_URI = "mongodb+srv://0802shruti04:kZpEOuy0cSfaRVRY@cluster0.ainsa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",
    PORT = "4000"
  }

[frontend]
  service = "frontend"
  start = "npm start"
  build = "npm run build"
  env = { 
    NEXT_PUBLIC_API_URL = "https://your-backend-url-from-railway:4000",
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Y29zbWljLXRocnVzaC0zLmNsZXJrLmFjY291bnRzLmRldiQ",
    CLERK_SECRET_KEY = "sk_test_llSk0cpFlwGseFJ9rA7rTQB08G8ZXN0A2IUd5VH1iZ"
  }
